name: cookies
version: 0.0.1-dev
author: Michael Haubenwallner <michael.haubenwallner@gmail.com>
description: A client cookie library
homepage: https://plus.google.com/108931164613660994654
dependencies:
  unittest: any
  browser: any
